[project]
name = "kagent-claude-sdk"
version = "0.1.0"
description = "Kagent integration for Claude Agent SDK"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kagent-core",
    "claude-agent-sdk>=0.1.3",
    "a2a-sdk>=0.3.8",
    "fastapi>=0.115.0",
    "httpx>=0.27.2",
    "pydantic>=2.0.0",
    "uvicorn>=0.30.0",
    # Dependencies for OpenTelemetry instrumentation (required by kagent-core)
    "anthropic>=0.31.0",
    "google-genai>=1.21.1",
    "openai>=1.0.0",
]

[tool.uv.sources]
kagent-core = { workspace = true }

[project.scripts]
kagent-claude-sdk = "kagent.claude_sdk.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kagent"]
