# Agent-level permissions configuration
# Configure which users/groups can access which agents

# Example: Restrict k8s-agent to SRE team
# agent_permissions:
#   kagent/k8s-agent:
#     user_groups:
#       - S0T8FCWSB  # Replace with your Slack user group ID
#     users:
#       - admin@company.com
#     deny_message: "K8s agent requires @sre-team membership"
#
#   kagent/observability-agent:
#     user_groups:
#       - S1A2B3C4D  # Replace with your Slack user group ID
#     users: []
#     deny_message: "Observability agent requires @monitoring-team membership"
#
#   kagent/helm-agent:
#     # Public - no restrictions
#     user_groups: []
#     users: []

# Default: If agent not listed above, it's public (accessible to all)
agent_permissions: {}

# Global settings
settings:
  user_group_cache_ttl: 300  # 5 minutes
