---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kagent-slackbot
  namespace: kagent-slackbot
  labels:
    app: kagent-slackbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kagent-slackbot
  template:
    metadata:
      labels:
        app: kagent-slackbot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kagent-slackbot
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: slackbot
        image: kagent-slackbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: kagent-slackbot-secrets
              key: slack-bot-token
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: kagent-slackbot-secrets
              key: slack-app-token
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: kagent-slackbot-secrets
              key: slack-signing-secret
        envFrom:
        - configMapRef:
            name: kagent-slackbot-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: permissions-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: permissions-config
        configMap:
          name: kagent-slackbot-config
          items:
          - key: permissions.yaml
            path: permissions.yaml
